project:
  type: website
  output-dir: docs

website:
  title: "Dongah Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true



